[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"
NITRO_PRESET = "netlify"

[[redirects]]
from = "https://release.ultravires.me/*"
to = "https://releases.ultravires.me/:splat"
status = 302
